### ISSUE TITLE
No sound on linux

### ISSUE THREAD

**Issue by GeorgeWoody** [Wintermute0110/plugin.program.advanced.emulator.launcher#11]
How can I fix the problem of no sound on linux when I launch an emulated game??

Using AL, I use a script to suspend kodi and launch a game; and I modify "launcher_plugin.py" file (~/.kodi/addons/plugin.program.advanced.launcher-master/resources/lib) in order to get both KODI and Advanced Launcher working with ALSA driver... but I cant find a solution for AEL

Really dont know if this is an issue per se... but for me it really is D:

Great addon BTW

**Comment by Wintermute0110** [comment]
This problem is not related with AEL. However, in order to speed up the launching process I disabled suspending audio in Kodi.

You can create a mixer device in ALSA and that will solve your problem. Another solution is to install pulseaudio. Search the Kodi forum, there are many answers about this matter.

**Comment by GeorgeWoody** [comment]
My script conf that launch rom/retroarch work well with both, AL and AEL, the only difference is the modification of launcher_plugin.py (an esoecific AL file) file, that not exist in AEL. That file do the trick with no sound problem...

Your addon is really, really fast :D

**Comment by Wintermute0110** [comment]
`launcher_plugin.py` has become `main.py`. 

I see the modification you did. In both AL/AEL, audio was suspended in Kodi ONLY if you choose "Stop" or "Pause" on Settings --> Advance. I have recently commented that code in AEL because when launcher is done you have to call audioResume(), and that causes a several seconds delay.

I know pulseaudio is laggy sometimes, but solves most audio problems.  Best solution for your problem, if you want to keep using ALSA, is to create a dmixed sound card, and make that card the default. You will be able to use Kodi and the emulator at the same time without problems, without suspending audio in Kodi. Have a look here (if you google a bit you will find much better tutorials, and also there is material about this in the Kodi forum),

http://alsa.opensrc.org/Hardware_mixing,_software_mixing

I am very interested in a correct functioning under Linux since I'm a Linux user myself :)

**Comment by GeorgeWoody** [comment]
There's no way. Took the easy way installing pulseaudio, kodi works with audio, but retroarch,  having change audio driver to pulse... Still no working :(
I know is not an AEL issue, but, give me a hand :)
Really wanna move from AL to AEL

**Comment by Wintermute0110** [comment]
OK, I see. Uninstall pulseaudio and roll back to ALSA. Then, you need to configure software mixing with ALSA so several devices can use ALSA at the same time. In my setup I did it (it took some time, though). However, in the end I decided to buy a cheap USB sound card so Kodi sounds are routed through the USB sound card to my Denon speaker and Retroarch/Mednafen play on the TV.

Here you have another example to configure ALSA dmix for a 5.1 sound card,

https://wiki.gentoo.org/wiki/ALSA#Soundcard_only_available_for_one_application

With this configuration, you will be able to use your sound card with several applications simultaneously without suspending audio in Kodi. Please have a try and good luck!
