### ISSUE TITLE
add an autodetect emulator function

### ISSUE THREAD

**Issue by yreb** [Wintermute0110/plugin.program.advanced.emulator.launcher#22]
Hello

I tried your add-on on my new remix mini pc (RCB don't work on that device). Your add on seems to the work , but i have an other problem. installed app (and emulators) seems to be installed on the root part of my storage, (that device can't be root), it is also impossible to move that app to sd card.
 It seems to be impossible to link emulators directly.

I tried a move the app to sd solution => impossible due to that OS

emulators are detected as android app on kodi programs page..... there is no logic in that situation.

Could you add an autodetect function for emulator ? That could solve the problem for many users

**Comment by Wintermute0110** [comment]
I cannot add an emulator autodetect because there are hundredths of alternatives/options depending on the platform an user preferences. AEL is a general emulator front-end and launcher application and users are supposed to know how to launch applications. Maybe request some help in Kodi forum, AEL thread and somebody will be able to help you.

http://forum.kodi.tv/showthread.php?tid=287826
