### ISSUE TITLE
Trailers Cont. to play.

### ISSUE THREAD

**Issue by eggfoo** [Wintermute0110/plugin.program.advanced.emulator.launcher#25]
Im using the Sexy Cirrus skin currently. 
Using Jarvis.
most recent version of AEL this issue was noticed.
Did not happen with previous version.

I have the option for "play trailer, in Window" on.
when i move to a file. after 1 or 2 secs. the trailer (ive selected) auto starts to play. If i move to a new rom file. the trailer stops playing. and if that newly selected rom has a trailer that will start to play..
The issue is: Previously when i would ESC or BACKSPACE to go back a step. the trailer would stop playing.

it doesnt anymore.

It stops playing when i launch the emulator though. just it keeps playing when i go back a step is kodi.

**Comment by Wintermute0110** [comment]
OK... Sexy Cirrus people are working on a new skin specifically tailored for AEL, and that skin is only for Krypton and up. Also, due to some changes in the Kodi core that are beneficial for AEL, AEL 0.9.5 and up will only work on Krypton. 

Conclusion is: I think is not worth spending time on Jarvis stuff and concentrate on the future. Let's wait a little bit until Krypton is out, new stuff is out, everything stabilises. Then, I will try to solve any issue you may have with the trailers, OK? I will close issue now.
