### ISSUE TITLE
multiple emulators per launcher?

### ISSUE THREAD

**Issue by nonekiller001** [Wintermute0110/plugin.program.advanced.emulator.launcher#38]
Could you add the option to use multiple emulator per launcher. similar to how the additional argument work: when you select a rom it will ask you which launcher you want to use. I.e if i set the 2 emulators as retroarch hatari and standalone hatari it will ask me which one to launch the rom with. This will allow me to play rom that do not work in the retroarch cores.(i ussualy prefer using retroarch cores when possible because of shaders and easy controller set up.) As well as easily launch different emulators as the mood arises such as the 3dnes emulator, sometimes i want to try a rom in that emulator.

**Comment by Wintermute0110** [comment]
OK, I know what you mean. Additional arguments are easy to manage because all of them are associated with the same executable. If I add additional executables, each with its own set of additional arguments it will be difficult to manage with Kodi limited GUI.

In my setup I also have different emulators for the same ROM set: for example, for SMS ROMs I have Retroarch plus MAME. I think it's easier to create separate launchers for different emulators than having a complex launcher which supports several emulators.
