### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by lilbud** [Wintermute0110/plugin.program.advanced.emulator.launcher#45]
I've been trying to set up AEL, but ran into a problem. How would I set up retroarch? I can't find the retroarch program to launch games. Retroplayer doesn't work for me and no games run.

**Comment by Wintermute0110** [comment]
What operating system do you have?

**Comment by lilbud** [comment]
Running the latest version of LibreELEC on the Raspberry Pi 3.

**Comment by Wintermute0110** [comment]
OK, then I recommend you use the GameStarted addon. Look for it in the Kodi forum. LibreELEC is a very minimalistic distribution of Linux with only a subset of the software and commands available in a normal Linux distro, like Debian or Ubuntu. In order to run Retroarch you will need to install a Retroarch package that contains the binary version of Retroarch ready to use on LibreELEC.

**Comment by lilbud** [comment]
I have used the Gamestarter repository multiple times, could never get it set up correctly.

**Comment by Wintermute0110** [comment]
In LibreELEC you have to install Retroarch since it is not included in the default stock distribution. I believe GameStarter is your best bet, ask for help in their thread if you need it. Also, the [RetroPie wiki](https://github.com/RetroPie/RetroPie-Setup/wiki) has a lot of Retroarch-related information. Some bits may not be applicable to LibreELEC and some of the config files may be in different locations but it is an invaluable resource.
